### ISSUE TITLE
인증 프로세스 적용을 위한 인증 api 개발

### ISSUE THREAD

**Issue by beaniejoy** [beaniejoy/dongne-cafe-api#17]
- 멀티프로젝트로 전환
  - `dongne-account-api`
  - `dongne-service-api`
- 기능 구현
  - 우선 인증 처리 기능만 적용할 것(인가는 추후 적용)
  - 회원가입, 로그인까지
- 스펙
  - Spring Security 적용
  - 다른 외부 모듈 연동하지말고 순수 Security와 Session, DB만으로 구성해볼 것

**Comment by beaniejoy** [comment]
## 궁금한 내용
```kotlin
override fun onAuthenticationFailure(
  request: HttpServletRequest,
  response: HttpServletResponse,
  exception: AuthenticationException
) {
  val signInRequest = objectMapper.readValue(request.reader, SignInRequest::class.java)
  //...
}
```
아래와 같은 에러 발생
```
java.io.IOException: Stream closed
	at org.apache.catalina.connector.InputBuffer.throwIfClosed(InputBuffer.java:526) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:432) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at org.apache.catalina.connector.CoyoteReader.read(CoyoteReader.java:108) ~[tomcat-embed-core-9.0.63.jar:9.0.63]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:276) ~[jackson-core-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2442) ~[jackson-core-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:698) ~[jackson-core-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3642) ~[jackson-databind-2.13.3.jar:2.13.3]
	at io.beaniejoy.dongnecafe.common.security.handler.ApiAuthenticationFailureHandler.onAuthenticationFailure(ApiAuthenticationFailureHandler.kt:27) ~[main/:na]
```
중간에 reader close 된 것인지 궁금(아직 해결 못한 부분)

**Comment by beaniejoy** [comment]
## Blog Post
- [[Spring] 설정파일과 Bean 사이의 순환참조(circular references) 이슈 및 해결](https://beaniejoy.tistory.com/85)
